from enum import Enum

class Countries:
    def __init__(self) -> None:
        self.list_of_countries=[
            'AT',
            'BE',
            'BG',
            'CH',
            'CY',
            'CZ',
            'DK',
            'EE',
            'EL',
            'ES',
            'EU27_2020',
            'FI',
            'FR',
            'HR',
            'HU',
            'IS',
            'IT',
            'LI',
            'LT',
            'LU',
            'LV',
            'MT',
            'NL',
            'NO',
            'PL',
            'PT',
            'RO',
            'SE',
            'SI',
            'SK',
            'DE',
            'DE_TOT',
            'AL',
            'EA18',
            'EA19',
            'EFTA',
            'IE',
            'ME',
            'MK',
            'RS',
            'AM',
            'AZ',
            'GE',
            'TR',
            'UA',
            'BY',
            'EEA30_2007',
            'EEA31',
            'EU27_2007',
            'EU28',
            'UK',
            'XK',
            'FX',
            'MD',
            'SM',
            'RU']
    
    def generate_countries_enum(self):
        return Enum('Countries', ((x,x)for x in self.list_of_countries))